[card:mt6768-mt6358]
name = "MediaTek MT6768"

[verb:HiFi]
playback_pcm = 2
enable "ADDA_DL_CH1 DL2_CH1"
enable "ADDA_DL_CH2 DL2_CH2"

[verb:HiFi/device:Speaker]
channels = 1                              ; speaker path is mono on Realme C25 series
conflicts = "Headphones"
enable "LOL Mux" = 2                      ; item 2 "Playback"
enable "Ext_Speaker_Amp Switch"
enable "SpkrLeft Sia81xx Power" = 1       ; item 1 "On"

[verb:HiFi/device:Headphones]
conflicts = "Speaker"
enable "HPL Mux" = 2                      ; item 2 "Audio Playback"
enable "HPR Mux" = 2                      ; item 2 "Audio Playback"
disable "Ext_Speaker_Amp Switch"
disable "SpkrLeft Sia81xx Power"          ; item 0 "Off"
