backlight_path = /sys/class/leds/lcd-backlight/brightness
alsa_card = 0
max_brightness = 2047
screen_blank_supported = false
lvgl_thread_affinity = 6 7
audio_thread_affinity = 5
status_bar_height_dp = 38
